version: "3.9"
services:
  db:
    container_name: container_postgres_ausbildung
    image: postgres:15
    restart: always

    environment:
      POSTGRES_DB: ausbildung_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports: ["5435:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data         
      - ./initdb:/docker-entrypoint-initdb.d    

  web:
    build: .
    container_name: container_webserver_ausbildung

    image: jetty:12-jdk17-webapp
    ports: ["8085:8080"]

    depends_on:
      - db # start db first

volumes:
  pgdata:
